// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gudcvzrnfpisyfmfpxzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1ZGN2enJuZnBpc3lmbWZweHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NjU1MDksImV4cCI6MjA2ODE0MTUwOX0.fX_x27C2iv9NQv9B7sB-L46VKfCYvqEeVJSwZdbaZaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});